

DROP TABLE IF EXISTS QRTZ_EXECUTE;
CREATE TABLE QRTZ_EXECUTE(
  ID INT8,
  PID INT8,
  EXECUTE_IDX INT4,
  JOB_TYPE VARCHAR(8),
  STATE VARCHAR(10),
  CRON VARCHAR(50),
  ZONE_ID VARCHAR(50),
  REPEAT_COUNT INT4,
  REPEAT_INTERVAL INT4,
  TIME_TRIGGERED INT8,
  PREV_FIRE_TIME INT8,
  NEXT_FIRE_TIME INT8,
  HOST_IP VARCHAR(50),
  HOST_NAME VARCHAR(80),
  START_TIME INT8,
  END_TIME INT8,
  PRIMARY KEY (ID)
);

ALTER TABLE QRTZ_EXECUTE ADD CONSTRAINT IDX_QRTZ_EXECUTE_UNIQUE UNIQUE (PID,JOB_IDX);

COMMENT ON TABLE QRTZ_EXECUTE IS '定时任务::执行配置表';
COMMENT ON COLUMN QRTZ_EXECUTE.ID IS '主键';
COMMENT ON COLUMN QRTZ_EXECUTE.PID IS '关联任务';
COMMENT ON COLUMN QRTZ_EXECUTE.EXECUTE_IDX IS '任务/触发器标签';
COMMENT ON COLUMN QRTZ_EXECUTE.JOB_TYPE IS '任务类型';
COMMENT ON COLUMN QRTZ_EXECUTE.STATE IS '任务状态 传入_默认INIT(EXECUTING.执行中 PAUSED.暂停 COMPLETE.完成 ERROR.异常 INIT.初始化/未启动）';
COMMENT ON COLUMN QRTZ_EXECUTE.CRON IS 'CRON:cron表达式';
COMMENT ON COLUMN QRTZ_EXECUTE.ZONE_ID IS 'CRON:时区';
COMMENT ON COLUMN QRTZ_EXECUTE.REPEAT_COUNT IS 'SIMPLE:重复/执行次数';
COMMENT ON COLUMN QRTZ_EXECUTE.REPEAT_INTERVAL IS 'SIMPLE:执行时间间隔';
COMMENT ON COLUMN QRTZ_EXECUTE.TIME_TRIGGERED IS 'SIMPLE:执行时间';
COMMENT ON COLUMN QRTZ_EXECUTE.PREV_FIRE_TIME IS '上一次执行时间';
COMMENT ON COLUMN QRTZ_EXECUTE.NEXT_FIRE_TIME IS '下一次执行时间';
COMMENT ON COLUMN QRTZ_EXECUTE.HOST_IP IS '执行机器地址';
COMMENT ON COLUMN QRTZ_EXECUTE.HOST_NAME IS '执行机器名称';
COMMENT ON COLUMN QRTZ_EXECUTE.START_TIME IS '开始时间';
COMMENT ON COLUMN QRTZ_EXECUTE.END_TIME IS '结束时间';



-- QrtzExecute


id
pid
executeIdx
jobType
state
cron
zoneId
repeatCount
repeatInterval
timeTriggered
prevFireTime
nextFireTime
hostIp
hostName
startTime
endTime