
-- QRTZ_APP
DROP TABLE IF EXISTS QRTZ_APP;

CREATE TABLE QRTZ_APP(
  APPLICATION VARCHAR(50) COMMENT '调度名称/应用名称',
  STATE VARCHAR(10) NOT NULL COMMENT '状态 N.停止/不可用  Y.开启/可用',
  TIME_PRE  int8 DEFAULT -1 COMMENT '上一次check时间',
  TIME_NEXT int8 NOT NULL COMMENT '下一次check时间',
  TIME_INTERVAL INT8 COMMENT 'check的检查间隔(毫秒)',
  PRIMARY KEY (APPLICATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时任务::应用表' ;

-- QRTZ_NODE
DROP TABLE IF EXISTS QRTZ_NODE;
CREATE TABLE QRTZ_NODE(
  APPLICATION VARCHAR(50) COMMENT '调度名称/应用名称',
  HOST_IP VARCHAR(50) NOT NULL COMMENT '实例机器IP',
  HOST_NAME VARCHAR(80) NOT NULL COMMENT '实例机器名称',
  STATE CHAR(1) NOT NULL COMMENT '状态 N.停止/不可用  Y.开启/可用',
  TIME_CHECK INT8 NOT NULL COMMENT '检查时间',
  PRIMARY KEY (APPLICATION,HOST_IP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时任务::节点实例表' ;

-- QRTZ_JOB
DROP TABLE IF EXISTS QRTZ_JOB;
CREATE TABLE QRTZ_JOB(
  ID INT8 COMMENT '主键',
  APPLICATION VARCHAR(50) NOT NULL COMMENT '调度名称/应用名称',
  STATE VARCHAR(10) NOT NULL COMMENT '任务状态 传入_默认INIT(EXECUTING.执行中 PAUSED.暂停 COMPLETE.完成 ERROR.异常 INIT.初始化/未启动）',
  JOB_CLASS VARCHAR(127) NOT NULL COMMENT '任务全类名',
  JOB_DATA VARCHAR(255) COMMENT '任务数据',
  JOB_DESCRIPTION VARCHAR(100) COMMENT '任务描述',
  UPDATE_TIME INT8 NOT NULL COMMENT '更新时间',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COMMENT='定时任务::任务配置表' ;
-- ALTER TABLE QRTZ_JOB ADD CONSTRAINT IDX_QRTZ_JOB_UNIQUE UNIQUE (JOB_IDX,JOB_CLASS);


-- QRTZ_EXECUTE
DROP TABLE IF EXISTS QRTZ_EXECUTE;
CREATE TABLE QRTZ_EXECUTE(
  ID INT8 COMMENT '主键',
  PID INT8 NOT NULL COMMENT '关联任务(QRTZ_JOB::ID)',
--  EXECUTE_IDX INT4 NOT NULL,
  JOB_TYPE VARCHAR(8) NOT NULL COMMENT '任务类型',
  STATE VARCHAR(10) NOT NULL COMMENT '任务状态 传入_默认INIT(EXECUTING.执行中 PAUSED.暂停 COMPLETE.完成 ERROR.异常 INIT.初始化/未启动）',
  CRON VARCHAR(50) COMMENT 'CRON:cron表达式',
  ZONE_ID VARCHAR(50) COMMENT 'CRON:时区',
  REPEAT_COUNT INT4 COMMENT 'SIMPLE:重复/执行次数',
  REPEAT_INTERVAL INT4 COMMENT 'SIMPLE:执行时间间隔',
  TIME_TRIGGERED INT8 DEFAULT -1 COMMENT 'SIMPLE:已執行次數，儅REPEAT_COUNT>時才會被統計',
  PREV_FIRE_TIME INT8 DEFAULT -1 COMMENT '上一次执行时间',
  NEXT_FIRE_TIME INT8 COMMENT '下一次执行时间',
  HOST_IP VARCHAR(50) NOT NULL COMMENT '最后操作:执行机器地址',
  HOST_NAME VARCHAR(80) NOT NULL COMMENT '最后操作:执行机器名称',
  START_TIME INT8 NOT NULL COMMENT '任务开始时间',
  END_TIME INT8 DEFAULT -1 COMMENT '任务结束时间,<1时没有结束时间',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时任务::执行配置表' ;

-- ALTER TABLE QRTZ_EXECUTE ADD CONSTRAINT IDX_QRTZ_EXECUTE_UNIQUE UNIQUE (PID,EXECUTE_IDX);
create INDEX QRTZ_EXECUTE_PID_IDX on QRTZ_EXECUTE (PID);


